# Generated by Django 4.0.4 on 2022-07-08 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chofer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=3000)),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_empresa', models.IntegerField(unique=True)),
                ('dv_empresa', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pasajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField(unique=True)),
                ('dv', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('telefono', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chofer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.chofer')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.destino')),
                ('pasajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.pasajero')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=6, unique=True)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.modelo')),
                ('tipo_vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipo_vehiculo')),
            ],
        ),
        migrations.AddConstraint(
            model_name='pasajero',
            constraint=models.CheckConstraint(check=models.Q(('rut__range', (1000000, 40000000))), name='check_pasajero_rut'),
        ),
        migrations.AddConstraint(
            model_name='pasajero',
            constraint=models.CheckConstraint(check=models.Q(('dv__in', '0123456789K')), name='check_pasajero_dv'),
        ),
        migrations.AddConstraint(
            model_name='pasajero',
            constraint=models.CheckConstraint(check=models.Q(('telefono__range', (100000000, 999999999))), name='check_pasajero_telefono'),
        ),
        migrations.AddField(
            model_name='modelo',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.marca'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.CheckConstraint(check=models.Q(('rut_empresa__range', (48000000, 99000000))), name='check_empresa_rut'),
        ),
        migrations.AddConstraint(
            model_name='empresa',
            constraint=models.CheckConstraint(check=models.Q(('dv_empresa__in', '0123456789K')), name='check_empresa_dv'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
        migrations.AddField(
            model_name='chofer',
            name='vehiculo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='proyecto.vehiculo'),
        ),
        migrations.AlterUniqueTogether(
            name='modelo',
            unique_together={('marca', 'descripcion')},
        ),
        migrations.AddConstraint(
            model_name='chofer',
            constraint=models.CheckConstraint(check=models.Q(('rut__range', (1000000, 40000000))), name='check_chofer_rut'),
        ),
        migrations.AddConstraint(
            model_name='chofer',
            constraint=models.CheckConstraint(check=models.Q(('dv__in', '0123456789K')), name='check_chofer_dv'),
        ),
        migrations.AddConstraint(
            model_name='chofer',
            constraint=models.CheckConstraint(check=models.Q(('telefono__range', (100000000, 999999999))), name='check_chofer_telefono'),
        ),
    ]
