# Generated by Django 4.0.4 on 2022-07-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chofer',
            options={'verbose_name_plural': 'Choferes'},
        ),
        migrations.AlterModelOptions(
            name='tipo_vehiculo',
            options={'verbose_name': 'Tipo vehiculo', 'verbose_name_plural': 'Tipos de vehiculo'},
        ),
        migrations.AddField(
            model_name='chofer',
            name='disponible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chofer',
            name='habilitado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='color',
            field=models.CharField(default='Grafito', max_length=50),
            preserve_default=False,
        ),
    ]
